#!{{pkgPathFor "core/bash"}}/bin/bash -e

{{#unless cfg.app.directory}}
    echo "app.directory must be configured"
    exit 1
{{/unless}}

cd "{{cfg.app.directory}}"

if [ -f "{{pkg.svc_config_path}}/env" ]; then
    echo "Loading environment from: {{pkg.svc_config_path}}/env"
    set -a
    source "{{pkg.svc_config_path}}/env"
    set +a
fi

exec nodemon

{{~ #if cfg.ext}} \
    --ext {{strJoin cfg.ext "," }}
{{~ /if ~}}

{{~ #each cfg.ignore}} \
    --ignore "{{this}}"
{{~ /each ~}}

{{~ #if cfg.debug.enabled}} \
    --inspect="{{cfg.debug.host}}:{{cfg.debug.port}}"
{{~ /if ~}}

{{~ #if cfg.app.script}} \
    "{{cfg.app.script}}"
{{~ /if ~}}

{{~ #each cfg.app.args}} \
    "{{this}}"
{{~ /each ~}}

    </dev/null \
    {{#if cfg.app.log}}>> "{{pkg.svc_var_path}}/{{cfg.app.log}}{{/if}}" 2>&1
