{{ #with cfg.wal-e.aws as |aws| }}
wale_s3_prefix='s3://{{aws.bucket}}/{{../../../svc.service}}-{{../../../svc.group}}'
aws_access_key_id='{{aws.access_key_id}}'
aws_secret_access_key='{{aws.secret_access_key}}'
aws_region='{{aws.region}}'
{{/with}}

[pg]
data_dir='{{pkg.svc_data_path}}'
superuser_name='{{cfg.superuser.name}}'
superuser_password='{{cfg.superuser.password}}'
