#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."


echo "==> Setting depot channel to unstable…"
export HAB_DEPOT_CHANNEL=unstable


#echo "==> Installing habitat package for postfix…"
#hab pkg install jarvus/postfix