#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
script/update


echo "==> Unloading habitat service jarvus/postfix…"
hab sup unload jarvus/postfix


echo "==> Loading habitat service jarvus/postfix…"
hab sup start jarvus/postfix