pkg_name=libX11
pkg_origin=core
pkg_version=1.6.4
pkg_description="Core X11 protocol client library"
pkg_upstream_url=https://github.com/mirror/libX11
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_source=https://www.x.org/archive/individual/lib/libX11-${pkg_version}.tar.bz2
pkg_shasum=b7c748be3aa16ec2cbd81edc847e9b6ee03f88143ab270fb59f58a044d34e441
pkg_include_dirs=(include)
pkg_lib_dirs=(lib)
pkg_build_deps=(
  core/gcc
  core/make
  core/autoconf
  core/automake
  core/libtool
  core/m4
  core/pkg-config
  jarvus/xorg-macros
  jarvus/libxtrans
  jarvus/libx11proto
  jarvus/xextproto
  jarvus/inputproto
  jarvus/kbproto
  jarvus/libxcb
  jarvus/libpthread-stubs
  jarvus/xcb-proto
  jarvus/libXau
)
pkg_deps=(
  core/glibc
  core/gcc-libs
  core/coreutils
)